=== douglasvinicio/XML/Family_2020/family.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Purpose : create the document type declaration for the family -->
<!-- Developed by Douglas Vinicio -->
<!-- Script Date : May 26, 2020 -->

<!-- Declare the family root element -->
<!ELEMENT family (mom, dad, elder_child, youngest_child,troubles?)>

<!-- Declaring each element -->
<!ELEMENT mom (#PCDATA)>
<!ELEMENT dad (#PCDATA)>
<!ELEMENT elder_child (#PCDATA)>
<!ELEMENT youngest_child (#PCDATA)>

<!-- Declare troubles elements -->
<!ELEMENT troubles (trouble, more_trouble)>
<!ELEMENT trouble (#PCDATA)>
<!-- More trouble -->
<!ELEMENT more_trouble ((dog | cat)?)>
<!ELEMENT dog (#PCDATA)>
<!ELEMENT cat (#PCDATA)>

=== douglasvinicio/XML/Family_2020/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "family.dtd">
<family>
    <mom>Eleanor</mom>
    <dad>Marc</dad>
    <elder_child>Steven</elder_child>
    <youngest_child>John</youngest_child>
    <troubles>
        <trouble></trouble>
        <more_trouble>
            <cat>Kitty</cat>
        </more_trouble>
    </troubles>
</family>
